pathways:
  default: workshop

  paths:
    workshop:
      title: "Workshop"

      steps:
      - 00-workshop-overview
      - 01-prepare-for-launch
      - 02-deploy-our-first-app
      - 03-deeper-dive-on-apps
      - 04-services
      - 05-scaling
      - 06-troubleshooting
      - 99-workshop-summary

# modules:
# - name: 00-workshop-overview
#   title: Workshop Overview
# - name: 01-workshop-instructions
#   title: Workshop Instructions
# - name: 99-workshop-summary
#   title: Workshop Summary

params:
- name: TANZU_PLATFORM_PROJECT
  value: undefined
- name: DB_PASSWORD
  value: undefined

