pathways:
  default: workshop

  paths:
    workshop:
      title: "Workshop"

      steps:
      - 00-workshop-overview
      - 01-login-to-tp4k8s
      - 02-tp-concepts
      - 03-cluster-group-capabilities
      - 04-attach-cluster
      - 99-workshop-summary
params:
- name: TANZU_PLATFORM_PROJECT
  value: undefined

