pathways:
  default: workshop

  paths:
    workshop:
      title: "Workshop"

      steps:
      - 00-workshop-overview
      - 01-platform-engineers
      - 02-login-to-tp4k8s
      - 03-tp-concepts
      - 04-cluster-group-capabilities
      - 05-attach-cluster
      - 99-workshop-summary
params:
- name: TANZU_PLATFORM_PROJECT
  value: undefined

