apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-tanzu-platform-developer-experience"
spec:
  title: "Tanzu Platform Developer Experience"
  description: "The workshop covers the developer experience of deploying applications to the Tanzu Platform."
  publish:
    image: "$(image_repository)/lab-tanzu-platform-developer-experience-files:$(workshop_version)"
  workshop:
    files:
    - image:
        url: "$(image_repository)/lab-tanzu-platform-developer-experience-files:$(workshop_version)"
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
    packages:
    - name: tanzu-cli
      files:
      - githubRelease:
          slug: vmware-tanzu/tanzu-cli
          tagSelection:
            semver:
              constraints: ">=1.3.0 <1.4.0"
          # only download specific assets (optional; v0.12.0+)
          assetNames: ["tanzu-cli-linux-amd64.tar.gz"]
          disableAutoChecksumValidation: true
          unpackArchive:
            path: tanzu-cli-linux-amd64.tar.gz

  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      console:
        enabled: false
      docker:
        enabled: false
      registry:
        enabled: false
      vcluster:
        enabled: false
