#@ load("@ytt:data", "data")
---
apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-tanzu-platform-developer-experience"
spec:
  title: "Tanzu Platform Developer Experience"
  description: "The workshop covers the developer experience of deploying applications to the Tanzu Platform."
  publish:
    image: "$(image_repository)/lab-tanzu-platform-developer-experience-files:$(workshop_version)"
  workshop:
    image: "ghcr.io/tanzu-solutions-engineering/tanzu-platform-workshop/lab-devx-image:main"
    files:
    - git:
        url: https://github.com/Tanzu-Solutions-Engineering/tanzu-platform-workshop
        ref: origin/main
      includePaths:
      - /lab-tanzu-platform-developer-experience/workshop/**
      - /lab-tanzu-platform-developer-experience/exercises/**
      - /lab-tanzu-platform-developer-experience/README.md
      newRootPath: lab-tanzu-platform-developer-experience
  session:
    namespaces:
      budget: large
      security:
        token:
          enabled: false
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      console:
        enabled: false
      docker:
        enabled: true
      registry:
        enabled: true
      vcluster:
        enabled: false
    env:
    - name: KUBECONFIG
      value: /home/eduk8s/.config/tanzu/kube/config
    - name: PUBLIC_REGISTRY_HOST
      value: public-registry-$(session_name).$(ingress_domain)
    - name: TANZU_CLI_CLOUD_SERVICES_ORGANIZATION_ID
      value: #@ data.values.tanzu_platform.org
    - name: TANZU_PLATFORM_PROJECT
      value: #@ data.values.tanzu_platform.project
    - name: TANZU_PLATFORM_PROFILES
      value: #@ data.values.tanzu_platform.profiles
    - name: TANZU_PLATFORM_AVAILABILITY_TARGETS
      value: #@ data.values.tanzu_platform.availability_targets
    - name: TANZU_PLATFORM_DOMAIN
      value: #@ data.values.tanzu_platform.domain
    - name: TANZU_CLI_SPACE_CREATE_TOKEN
      value: #@ data.values.tanzu_platform.space_creation_token
    - name: DB_HOST
      value: #@ data.values.tanzu_platform.db_host
    - name: DB_PASSWORD
      value: #@ data.values.tanzu_platform.db_password
    ingresses:
    - name: public-registry
      host: $(session_name)-registry
      port: 5000
      protocol: http
      headers:
      - name: Authorization
        value: "Basic REGISTRY_BASIC_AUTH_CREDENTIALS"
      authentication:
        type: none
