apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: AvailabilityTarget
metadata:
  name: my-tkgs
  description: "Availability Target Multi Expression AND"
  namespace: default
spec:
   affinity:
      clusterAffinity:
         clusterSelectorTerms:
         - matchExpressions:
            - key: jaime-prod
              operator: Exists
              values: []
            - key: vsphere
              operator: Exists
              values: []
   description: ""
